apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  path: ./apps/cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
