apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-namespace
  namespace: flux-system
spec:
  interval: 1m
  path: ../namespaces/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
