apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  path: ./apps/metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb-namespace
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: controller
      namespace: metallb-system
