apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/minecraft
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: app