apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: transmission
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  path: ./apps/transmission
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: app
  dependsOn:
    - name: app-namespace
  suspend: true