apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/unifi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infra