apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  suspend: true
  interval: 1m
  path: ./apps/vaultwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: app
  dependsOn:
    - name: app-namespace
    - name: traefik

