apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wireguard
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/wireguard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infra 
  dependsOn:
    - name: infra-namespace
