apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
  - admin-sealed-secret.yaml
  - backup-sealed-secret.yaml
  - backup-restic-cronjob.yaml
