---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: cert-manager
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCTmV8r8KOCC9xKg2RnPcTZqzwWGmUFULZwyhFqEXXimXPbOjjHIurHvyASLynYTciSjIFYIxtpNgUW+gcBghLxMkKO10Cn3Cdc7e4pUIpcdtvlPWBFuVlk6xjOIBiEh0d/fDxbj6VKhz0pUybiCQaqMcxmqvkyKHebpXm1aHLKqHJlm+qjmqao9p9i2JuUrZsSZGE4ha+0qHtW9/2k2aDNlb5NyCV57477K3wE7II7BLA8eky+ee60oFu3NEFRVyA9Ze2+M3qf9gC5RgWb1DgAu0zAQI1k/fNSqbCtz87PiaNM6agomvhB4gz0G54HSZ6IhHW+q+UO7vPbIy/SYObjx4ZYus0nTMRTG0c0gxNXD54PjqSnbCWLaRZpwJCfenXL/BuRYxSvdlDaO4I3oeqJzdDkGbfcgcw0S3iNg5lqbqwebFqfrIVy6cNbXkRRPL/ANyy7AVJIiDnsEh8wM7ubt5eUvl7rOcJggpKbfl5gc/G/bVJckuXbxbFEUOY+IuWLkV1mR07Zbs9H1fW6gPXJAeDunAKMiZq6QarhTg1hrza/xzaZVpmT0kEIDI5F4n3GAO+tnzCBhF7jkUKAZM+1dY9P+9IYnkMT0zPWjVTzaOhFFEp7xK/FFwsoDi3pEBSQrRUI12qQ068xcrZheKmeW197ciqdO0K6KrHhwgfJxFpK4r702RkcUT0akhUGv0rEnu+dYMijVMxFLmuzjKNP/bE9Jw==
    AWS_SECRET_ACCESS_KEY: AgAYZ4Zyh7EnmrGURtW4JNij4j6fmSm+OYHAm640xIRzB229KdpPew5k45RkWRtJwQ6IauoJKgZpLd7EvwWi4fR3/IijeskBAD9fIFHI1E5awPgEi9wTiULtqB6rx6adh1az/35ZOL1hMurwD26MIEnwErRubbal22jCuW9Dnbor2qs84Mqt04s+7k5Fd6zEWCtgvMBs87vXet3FkfLozcyY2HcmTQI3z6DwuNq7Mp0m9+vHL7z+ntz+o4RcP9uZ02r7mou9vYj0bQvmHV8BOszpNuF8oZjI6CsjhLxlE7BZb39MkIxo/N1YJS2dgjANqVni0XpVjlxMI8KuEdWF73KgUnPz28QjYMRw0TTatspFTQFqqDu7GJnPl/bNtEBYVOa/oSjADJ6fQGCoyMpORA1zy3QHfVl16BmRTHIk+JPRfrsEe8c5il3VbBRlbQHr/qgCa16Sf+m7qXnk8Hl1v7jMXhVeluz8TrdIv6YzZS6yLm2qRUsxZdWFlM6oKn4jo/QofufI+PrgJVS1T4rhkFSxDkFGHd6/+wZmduBycbTDwx1DTyvFK2N3VDbdhy6+HfsfR3VFyuldbG3LSR0sAktmfEaSDYxvzUiF3pWRSwOuTm5y2om67lO6fS7Ja6gGVp4FxTrWBJMBhSKFcgHlm+waZ+PD094ypbTqMlb2HsYZ2ZKrrpVhHedOWSbXdbhSIFinO7vT+MLiFkzV9vSZS1jPxdPpkEKeKcmZ6ESAyqP8uWin+ZzfriAj
  template:
    metadata:
      name: aws-credentials
      namespace: cert-manager
