apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@danielvdp.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector: {}
      dns01:
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID
            namespace: cert-manager
          secretAccessKeySecretRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY
            namespace: cert-manager
