apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - aws-credentials-sealed-secret.yaml
  - cluster-issuer.yaml
  - wildcard-certificate.yaml
