apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-exporter-storage
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: nfs-exporter-storage
  resources:
    requests:
      storage: 16Ti
