---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpackerr-secret
  namespace: media
spec:
  encryptedData:
    RADARR_API_KEY: AgCUbamuNqw6RbKYrfoOZuyYSXOnid0NaLuz5/h98KiOFXPqnfFE+UP1Armdt9nM7PmIZQ8JRshY38F6vikXfOA9nUDgYKUyWrlO36zjwLYb9b8qpX18f1/5WdSStaWwVN4JGEoNLE0Kr5B4CNU6Q3UguzPEK7GJABgggIb/KAP8TqI6Ha51UURm5pEdONHEiNHPCoZofpc66yde07nHAtmd2GPBF7JsfSgI60nbm5o0pkDjzvTQpZu5EyLzDSMaY9DQPrP1vdqUrDtr1bqJRWxoJiLXHhUMEpGAvYCRb2ra34wX6+ndmosX9f2niRK3mKU221oYqWztYCmOifRuskpTb356UIDuOehZUNryLUkVTvSpTN6ioF3L5f8edEJKkYyaCd2JOlATshbD5wBMpJ7GEtPX1CKWLGljIU+HHsRymopl/LI9RdPZ4fEjHvAWFlODM0PNqXC3O7tGnGniPfzWnWDLq+5J9/fre2MNpqh8VB2qWYtksixwM9NkdNLjfJi9nuXevMSVQTAv/m/QHBEHPGJYaQCVCKHSulmZbkruhtKb29i8uSL3k6l6iI4x0HGRvYDLrOIf+NBfJrteeL0IPF2973ATjfAjevsk+51EYl2hYmP2Zo04lA4cK5uAULWvOmdY/e4X+2tvj3A1ktu4KLPT/tshzZl3q5ysJ2dNufpLB/4PdkdsWvsZKK/Z6jqSL3dUSJFI+Ciee48LBSUmCkOS31Ikzvt/8Mw2GUkQpA==
  template:
    metadata:
      name: unpackerr-secret
      namespace: media
    type: Opaque
