---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpackerr-secret
  namespace: media
spec:
  encryptedData:
    RADARR_API_KEY: AgCoE/eyHoYbzZBrS6NaEUbYR+LINa0w8tubWCZ8dSLO0YQ6qDXd+xdzAfbhMinq57xq+Lc1XLMxz3DF5eo3wmGWtQv5gZy3fLb1EaezzgtYS8MqiW/10AZ3umpqC9AklVtKQve+BRmp5c9TClIrbmLCghm4shyXAHS0vBG49cD4gjQnsSWi+NAClnp4a/SmduOi+EVv1qIAGHDUMD2SOeB5VkgoctpB2i7lME44HUU8eZJiNgzYxSE+NZWhsAsoOIErCUkQUmblDGLyP8KVniCixO5uo59mwRxRb6GsDGlghgJZFpU3ycYxDvrZRWuZ7Z7TCA1y9PlsRUmSJPuJcxKL16xSwcyw/dfvCCrNnKKTygb+J2zKlDco5nWrW9+MA6vovgPHZewdj3nD5YIJkYtHKKxrIh4bGwb4t7Nmbv5kU9x3FTLs7SQmGqwpgigr04Z9eDqy6BNL9oIO8NkzcqOC7Jpg7w4+GZNBoG9PQZRjeiliq/abfXcaTVnv66LyqzuFgdAElMjoQ7MXXntI5E1zOFxwALvpQR4E6W3yhW1z4SOByEEfr7dp8/hUm8HFjpef1q5UqmUBApOohPK6LdLbwnF7Xdp60Hg53RL22oonMbN57fiFfREfhi2+4sgsFlBrFy9JZtP4WgcotojINsIVmt8I2zbqFkjWl4QJKMaQ57qMUHo3mjTfUOtU9RGsLddfKpsSdfPHQlg0w0HiHgzSHihVN5z+KKqB5xsAo48XHQ==
    SONARR_API_KEY: AgCsmZ1nsVFSIwA1NOMLZkSZxkDK4SLp8uo1SNnoS2AVLviiDpLPcc46fCWGzf5pGgthNvhHnD5kI1MCBZyBO9sMCgOiCud6gdQ2QgnErZcbFSrmX69aVLUwzghF6WWsdb7BG7w2tRTwWSmiwQaUBtOCDzTpimbD6EEk7Ggi4kssYA7VBeatyWkOtux5SCAM6e8hg4AtYXkMixZizhQNqUmaHLr2oo43CPL2MeAYSQF7HNtU86o3Dm9WeSRwnO9YR2pkLSqBxp86W+Ep+hqZCSc3bKxewylVkVk4jIpDSgdjb3hIeXvRu3ZRoGdf/xH1/b29YTIk/32pXJIm/sMag3WslZw0tUu/ELZWBb3eEouwTfT2tx3DTT2SHrDK9EA2fBxOrqiwFHPer7U+6z5pRAwptQ5EE2zFonvfiL6FOO0U2t1RpBliBdL3Nb7d1W7Zf2h5764GYgW9e89599WvdOty1qin07DCf9RWWrVez8SFMUA4tcOv4+UmY9qM57ENK6guxVzhtmKZwroMcH/U8EoO7mXx4JQCYCZVWYCum9MpY+pDgSqyQHKt21Epvxy1Y/uI7Fv9A+uSpJ7b7iA48aJ6DE1LJtSy8uwy5aYpWxOB6cRzpm7D+AHiCfCp6onkSVLU1b3gpsslINNzVvtMNdWokK7WjpOS1fQyzw7QtlU4c+/WSTW8w+wxaNFZIxlLTdmgo/G8zID4UR07VmSUSXdavAK0Wxd7v7ducL6hB2GIwQ==
  template:
    metadata:
      name: unpackerr-secret
      namespace: media
