apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-mongodb-data-longhorn
  namespace: infra
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi