---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifi-credentials
  namespace: infra
spec:
  encryptedData:
    MONGO_PASS: AgCL/8THApy7GjAP+kppAziBqBZrrPJL2WL3LFtPtjGLmjFXg0DXq7wlo4S4dEOQovrT+UGqNV5HW2oqZtrtO+Ef4eysmb5FbL5Kl873ZNDmfb/NXdeWvxFI97F9kjOg4gJ1z+xqA7qnS6dN9yecZBNeT+ML9vQlUOjOY1m21TD/JhMWIcqu3S7mBtoeTlNzeJ3WbjbyT6Dv/JuVqyG3fgWPKTrC3nBbiL/L3tWykjyKVwnbcve36h8+IugAVCY9pFNtgjwSmN8LcLM8Ryh2MfwC28wCJiCovxHzeIzkvO8NFx0vmbjZlff1ofPbgrL2zqnmwkcL9ltEtSla4NjuBBTXl4FGSYM9NqlD39+euITP2nusnyIC0qG5L7AK+DwU4ytkY1G8TJB5huAur2qSdeirDClmzu/7b0pauo67XgVJcc7IbTUIMqFv3OSmkWST+wTZ/DWLgtyMdeBka1AAHi2Sy1qLUAGoLKKjypypHr15WK6H8FvigF1HJ8P1mXlJXXqyGGB5ZnwLvvwU/sXUD63g20/oLd2BFkPoPYcCXW8lJj+iWpWwGls73CW1Sm4tFaRBNF9vEts3YF3cnbTdHUTWblGz8pbsHJDPztZOH1+hDebhuSsmJqXHSLVbLuND+RwW4jKdZfBjCErnRxlpRT0Aa1TDuFZXmatuorGeOirr9+4MLhxiUvYcOF/vAa6SGWJ0r0C0Ytld2dbdsB6lTudiqKUtb/cSqI6bmy428gIJDCBOqD8lfkhO2KOt00odKes=
    MONGO_USER: AgCZC8L7TIPh2jm0/7qDd9QbdqZ2LwpsrerkJ72wiLuiBz6SPEZ4KGiGXfzzsBPg3SykhyN6rkcVIjlDE9iPcKJCq4CZly3ZHPVxbARtp/W2VAsCBJxRLEI4sP9xn5VrBh7vyPrOPnDOta4KJoDDlzBxZPe74eO8LnvZC1MDxDqZk/imBSP/wTujPUc/NRAlw7rZYaRHYtCTErZzkz+qf4ABHfRY8Dm5lm13HNBlhaF4y7dY6gRrtmvn0P6qNFl73oz2WjnQn+5Hetz3DJOq+1W24eO7b7svxejCgVnkSxJeHzN0EY7BhhJJqy26Y58OX5MFRq4fN8scOnvLqdIZknigV/POaYugi7UrbxSkHvuZRgVB8+TcgCZnMc2Ps9xGQ8f2QvrAtFDGjL9ApVGfhdF+ei1TufwhJhK8KQLi2PYexRCD4oPlL9MhrwSGuWiFAhRVgDmb3uICtIsoSIUhqQQa9NYE4V/7g6APHfCLqB4DFNgVo+yQvDpH9NuLcz7cS+nA1MgrDzvUj/2fHr79/uZTakRB5SZS4RnJNX1bX1/sx3PHh6wymuOieCjfxGyf+Ng+Kpdzw0+D+rQH6fekPOHwxjWePzk668UYG72ZWFoI2U8GvZlXFODI9Q0FwXZ4isR03zXiXzO5339JAAPa+4NSiCw7L57xmd+QMlS3gjdAH+CidZgbhtN78djULvpbsyx32VtFrQ==
  template:
    metadata:
      creationTimestamp: null
      name: unifi-credentials
      namespace: infra
    type: Opaque
