apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: sealed-secrets-controller