apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-credentials
  namespace: app
spec:
  encryptedData:
    DB_PASSWORD: AgAoRY1AqHcvOXBOFTI2tpbGbno6XeKCjKFiVuEpcnN6C5QqsbRlX/XJzoaKwUK4ZtzQ1LM53Er5ZVdQEJlEgVdgNkhxlUSixFhL++/igT6ZImSfWytnqzndAjTljBLAycXRSfqn04WxpVxYMcy93a5jQl7K2SPxCFEw0jNvK0FfD2USgXz2N/4xrovTU6xl/Km3VslQGozzRaIbKd6+vN+g16u/jX/rwJFvCbN/hF5fDQpHXv+4VzxwZEcbbdcFltssKx7kykDfONRq5nBEXNq6dOS4AT6+KnA0XJSU0LVJGNM6UzjrH6v0aNkYO1ghU3F41eFcZri/Dt1ql1clsQXnwnx0v/grFtHfGm2vGPQAaDpL0n6SrIua4WPyoOK9yv60QJcgXtGyg96eTx56aAGzVKXy6W/j/xPOudHRl34BbDfA9YhJ72hHaOH5ptt6tdPcT9Sw8Zqzd5NrIK5+ZZrsanvfK47A/VaTOWz6PYefv7uI6UL+qMwCXB/+5A2AyAdFPeTki/Or2yKRURbgEiP0AY2qS8V+Aefqlza/zHLPu20mFVs6svEwk7NaeU9m4nH9esgM/OPNLU3F3TtOJmP4Xx3L2oAJ09kjSgjbgzw03cpusJnVxXBcBW27HoqIlRDlY8gBqTdqXmWGIj9VEXrXg4BAPxq52UIF6IsmbIhKt5s4sfZcCubW8MxPp1RjufciZgf6KXHbfsrBApjokzh56SxVYLlMi7oLsSuYKlE+
    DB_USERNAME: AgAwwpLiPjKK8X7rHHTMq6hskqDWp4dc0iFQ3HTf8xB9RQSiXEZ3HhE+GDa9NCGysjEUvNxnG5mpYvT9OxFpnU7PIh6a3a/LroSu2nAQ40qNG4g/Zd9kaxu/W1xRUfnmu6AZwQ7cw8kb+F59tpba3Uy7+KikXlxaFqFvQRmeeC2iRPv9FE0dFONRIfp2FEgzVOSdvarlN23QDfV/7wlUg2lQTWgoJoV0bkjiWovxAmtVw/oTzCJT7LyiD/r3m8t9MEppH9HX9v6u0qTNsfl08cV6ElzJYRzI7EFI8dzr46Sqrvhau+KMFshLy9vO4UVIVhzKhxtcQufaGtA7oLtt1TczpaohZoiSp3TQrKilmgJ+HvjQdQC3iU1jAfeKCdMp+hylII8zi34oqRL/VAXBX3uEgRSwG3Qq20/4zU+fOdAlziz/j9ia78h+jaJ9UmO0qJ+wXMU3ftOe3eupYMbJE7WniSOmqPfLsIh9Dq37w8x3yjslMOv6rv4eGtE81A1q/MKdQzAyLw8HIi+IugJprtMMqToEd3kIi7PNfNyVwamUsElIVbhm7jQeGxQAXRAdPf4JR1O2A1UKRUifnZt0lN5RlKY41USj0M3mDrSVYW3Kjvd9KdfA47z+UbBxGyVxzsVgh2mTACfD9Z2CEZW5NBz6OfSwdVuwT/mkRAtLjFHIsDtlCFUZ6JXAnceRW1EEBYQwolANPvs=
  template:
    metadata:
      name: immich-db-credentials
      namespace: app
    type: Opaque
