apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 10Ti
