apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: transmission-downloads
  resources:
    requests:
      storage: 16Ti
