apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: infra
data:
  traefik.yml: |
    api:
      insecure: true
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
