apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: infra
data:
  traefik.yml: |
    api:
      insecure: true
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    certificatesResolvers:
      letsencrypt:
        acme:
          email: me@danielvdp.com 
          storage: /data/acme.json
          dnsChallenge:
            provider: route53
            delayBeforeCheck: 30s
    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
