apiVersion: v1
kind: Service
metadata:
  name: docker-traefik
  namespace: infra
spec:
  type: ExternalName
  externalName: 192.168.0.210
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: docker-traefik
  namespace: infra
subsets:
- addresses:
  - ip: 192.168.0.210
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: docker-traefik-endpoint
  namespace: infra
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
