apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docker-traefik-fallback
  namespace: infra
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`^.+\.theorangeserver\.net$`)
      kind: Rule
      priority: 1  # Lowest priority - only matches if nothing else does
      services:
        - name: legacy-docker-traefik-endpoint
          port: 8080
          passHostHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: docker-traefik-fallback-https
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`bitwarden.theorangeserver.net`) || HostSNI(`radarr.theorangeserver.net`) || HostSNI(`sonarr.theorangeserver.net`) || HostSNI(`transmission.theorangeserver.net`) || HostSNI(`jackett.theorangeserver.net`) || HostSNI(`home.theorangeserver.net`) || HostSNI(`unifi-old.theorangeserver.net`)
      priority: 1
      services:
        - name: legacy-docker-traefik-endpoint
          port: 8443
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: infra
spec:
  insecureSkipVerify: true