apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-headers
  namespace: infra
spec:
  headers:
    customRequestHeaders:
      X-Real-IP: ""
      X-Forwarded-For: ""
      X-Forwarded-Proto: ""
      X-Forwarded-Host: ""