apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: syncthing
        image: syncthing/syncthing:2.0.9
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /rest/noauth/health
            port: 8384
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /rest/noauth/health
            port: 8384
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Adelaide"
        - name: STHOMEDIR
          value: "/config"
        ports:
        - name: web-ui
          containerPort: 8384
          protocol: TCP
        - name: sync
          containerPort: 22000
          protocol: TCP
        - name: discovery
          containerPort: 21027
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: mnt
          mountPath: /var/syncthing
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: syncthing
      - name: mnt
        nfs:
          server: 192.168.0.210
          path: /mnt/storage/sync
