apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-mnt
spec:
  capacity:
    storage: 16Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - hard
  nfs:
    server: 192.168.0.210
    path: /mnt/storage/sync
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
