apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-velocity-config
data:
  velocity.toml: |
    # Velocity configuration
    config-version = "2.7"
    
    # Network settings
    bind = "0.0.0.0:25577"
    motd = "<gradient:#ff6600:#ff9933>🍊 TheOrangeServer</gradient>"
    show-max-players = 15
    online-mode = true
    prevent-client-proxy-connections = false
    player-info-forwarding-mode = "modern"
    forwarding-secret-file = "/config/forwarding.secret"
    announce-forge = false
    kick-existing-players = false
    ping-passthrough = "DISABLED"
    
    # Server list
    [servers]
    main = "minecraft-backend:25565"
    create-ultimate-selection = "minecraft-create-ultimate-selection:25565"

    # Default server
    try = ["create-ultimate-selection", "main"]

    # Forced hosts - optional
    [forced-hosts]
    "vanilla.theorangeserver.net" = "main"
    "create.theorangeserver.net" = "create-ultimate-selection"
    
    # Advanced settings
    [advanced]
    compression-threshold = 256
    compression-level = -1
    login-ratelimit = 3000
    connection-timeout = 5000
    read-timeout = 30000
    haproxy-protocol = false
    tcp-fast-open = false
    bungee-plugin-message-channel = true
    show-ping-requests = false
    failover-on-unexpected-server-disconnect = true
    announce-proxy-commands = true
    log-command-executions = false
    log-player-connections = true
    
    # Query settings
    [query]
    enabled = false
    port = 25577
    map = "Velocity"
    show-plugins = false