apiVersion: v1
kind: Service
metadata:
  name: minecraft-atm10-sky-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.245
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: minecraft-atm10-sky
