---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-curseforge
  namespace: app
spec:
  encryptedData:
    cf-api-key: AgA7k7wHT6/+vxsqw6bFCNL1SdgYZJHSGAjuz3ZtIY3fIsJ2XlQ53XavSS7d+u7+5EHpitC8qNwXVMOTkmxH3EZqNXuwVCO2/kNesVmaltSmNbXIuB9XZyiPNlB/XdwF3unH3tYTqlE0suqchZIsbO4bGaU25U/Gus+nhUWPZ7bW0J4BaxuOwWYtG636mQVxIOKe6wmyVa/2YdP21tKqVltM0DIwRCTdJ6GPIs9T5r1TCtjLGrtYEEkadbeiEn7HkEv+yEo7so/PtiQWgSEW9C/qDLTRNiuIkR2TgpI3G81ratilgxkxUuPrCjNolhMJKIxlBCqmMgi0BMluyqHWMDSYlEbyFtf5MPpvUeP2rTcq+dknToE/+/qK49OVETpBOeAi6a86fBk+UG1L+JyvGhTeasDtEpFVrW+Ji9KR80V+2CSzX+RJYikMvi5JrH+EePJpGv+yWSh6pByV7VwEpPBKx9o3LaQhZpI7G6dvJxJjwXikU7CCsMM4k1CdULQOrM1ZObD2OyQCUFSo2TthZ/wh3rl9Lt76Nzr31FQKxNQqpIUdjrdP6io933K06Isx+4HJzu6s+XUMq/yL2b/7Ti1j83afKLVSY1JVlRsQKkporiWkygZrflMWRVrOWUPMj8j0jbnrzfTQBiyVf15H3tMEnNUja8hw2kZGJXkj/wDK5QyzbLMYo5ZQ4D+vakuPO44E
  template:
    metadata:
      name: minecraft-curseforge
      namespace: app
