apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - statefulset.yaml
  - velocity-deployment.yaml
  - services.yaml
  - pvcs.yaml
  - configmap.yaml
  - backuper-configmap.yaml
  - backup-sealed-secret.yaml
  - backup-restic-cronjob.yaml
  - rcon-sealed-secret.yaml
  - velocity-sealed-secret.yaml