apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-velocity-config
  annotations:
    volume.kubernetes.io/mount-options: "uid=1000,gid=1000"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
  annotations:
    volume.kubernetes.io/mount-options: "uid=1000,gid=1000"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
