apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-velocity-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-shared-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi