apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-backend
spec:
  serviceName: minecraft-backend
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-backend
  template:
    metadata:
      labels:
        app: minecraft-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: modron-01
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - minecraft-backend
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: fix-ownership
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          chown -R 1000:1000 /data
          chown -R 1000:1000 /data/world
          chown -R 1000:1000 /data/world_nether
          chown -R 1000:1000 /data/world_the_end
        volumeMounts:
        - name: data
          mountPath: /data
        - name: world
          mountPath: /data/world
        - name: world-nether
          mountPath: /data/world_nether
        - name: world-end
          mountPath: /data/world_the_end
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
      containers:
      - name: minecraft
        image: itzg/minecraft-server:2025.9.2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: VERSION
          value: "1.21.8"
        - name: MEMORY
          value: "8G"
        - name: USE_AIKAR_FLAGS
          value: "true"
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minecraft-rcon-secret
              key: rcon-password
        - name: RCON_PORT
          value: "25575"
        - name: SERVER_PORT
          value: "25565"
        - name: ONLINE_MODE
          value: "false"
        - name: PAPER_VELOCITY_SECRET
          valueFrom:
            secretKeyRef:
              name: minecraft-velocity
              key: forwarding-secret
        - name: WHITELIST
          value: "true"
        - name: ENFORCE_WHITELIST
          value: "true"
        - name: ENABLE_AUTOSTOP
          value: "FALSE"
        - name: VELOCITY_SECRET
          valueFrom:
            secretKeyRef:
              name: minecraft-velocity
              key: forwarding-secret
        - name: SPAWN_PROTECTION
          value: "0"
        - name: VIEW_DISTANCE
          value: "10"
        - name: MODE
          value: "survival"
        - name: DIFFICULTY
          value: "normal"
        - name: PAPER_VELOCITY_ENABLED
          value: "true"
        - name: PAPER_VELOCITY_ONLINE_MODE
          value: "true"
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - mc-health
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mc-health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            memory: "14Gi"
            cpu: "4000m"
          requests:
            memory: "10Gi"
            cpu: "1000m"
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "Pod terminating - saving world data gracefully"
                # Save the world before shutdown
                rcon-cli save-all
                sleep 2
        volumeMounts:
        - name: data
          mountPath: /data
        - name: world
          mountPath: /data/world
        - name: world-nether
          mountPath: /data/world_nether
        - name: world-end
          mountPath: /data/world_the_end
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data-longhorn
      - name: world
        persistentVolumeClaim:
          claimName: minecraft-world-longhorn
      - name: world-nether
        persistentVolumeClaim:
          claimName: minecraft-world-nether-longhorn
      - name: world-end
        persistentVolumeClaim:
          claimName: minecraft-world-end-longhorn
