name: Validate NixOS Config

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          echo "NIX_PATH=$HOME/.nix-profile" >> $GITHUB_ENV
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

      - name: Enable Experimental Features
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Validate NixOS Configuration
        working-directory: nixos
        run: nix flake check
